### ISSUE TITLE
Morning session code review

### ISSUE THREAD

**Issue by OscarFMdev** [MahdiSohaily/Awesome-books#3]
## Morning session code review Description

Your project is working perfectly, your JavaScript is clean, clear, and concise. Congratulations both! we think you can improve:

- [ ] Be sure that the user is not sending empty data, we think you can achieve this by using a required attribute to your text inputs.

### Cheers and happy coding! 🙌

**Comment by Kelvin-Ben** [comment]
# Awesome books: plain JavaScript with objects 
- Your project is great considering the fact that you have implemented javascript well.
- I can the local data storage script is well implemented.
- The add and remove buttons function well.
     # Happy Coding

**Comment by Alhajideen** [comment]
Hi guys,

Thank you for your observation(s) and contributions.
Kindly note that all the changes have been implemented and the issue will now be closed as completed.

Thank you 👍
